-version: 2
-jobs:
  build:
    cache_directories:
      - "~/fasma_data"

    dependencies:
      pre:
        - sudo apt-get update
        - sudo apt-get install gfortran
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        - chmod +x miniconda.sh && ./miniconda.sh -b
        - export PATH=/home/travis/miniconda2/bin:$PATH
        - conda update --yes conda
        - conda create -q -n test-environment python=2.7
        - source activate test-environment
        - make
        - cd MOOG; make -f Makefile.rh64silent

    test:
      override:
        - pytest --cov=. --cov-report term-missing --cov-config .coveragerc --durations 5
